
name: Build and release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build VSCode
        run: |
          ./build.sh vscode
      
      - name: Build CSS LSP
        run: |
          ./build.sh css-lsp

      - name: Release
        run: |
          ./build.sh prepare-release
          ./build.sh release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

